key_bindings:
  - { key: Return,   mods: Control|Shift, action: SpawnNewInstance }

# Colors (Nord)
colors:
   # Default colors
   primary:
     background: '#2E3440'
     foreground: '#D8DEE9'

   # Normal colors
   normal:
     black:   '#3B4252'
     red:     '#BF616A'
     green:   '#A3BE8C'
     yellow:  '#EBCB8B'
     blue:    '#81A1C1'
     magenta: '#B48EAD'
     cyan:    '#88C0D0'
     white:   '#E5E9F0'

   # Bright colors
   bright:
     black:   '#4C566A'
     red:     '#BF616A'
     green:   '#A3BE8C'
     yellow:  '#EBCB8B'
     blue:    '#81A1C1'
     magenta: '#B48EAD'
     cyan:    '#8FBCBB'
     white:   '#ECEFF4'
# Font configuration
font:
  normal:
    family: Fira Code
    style: regular
  bold:
    family: Fira Code
    style: Bold
  italic:
    family: Fira Code
    style: Italic

cursor:
  style:
    shape: Beam
    blinking: On
    blink_interval: 750
    blink_timeout: 5
