name: Add Minecraft whitelist

on:
  repository_dispatch:
    types: [minecraft_whitelist_add]


jobs:
  whitelist_add:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: |
          nix run .#minecraft-whitelist-add \
            ${{ github.event.client_payload.username }} \
            ${{ github.event.client_payload.id }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          title: Add users to minecraft whitelist
          branch: create-pull-request/mc-whitelist
          commit-message: "minecraft: Add ${{ github.event.client_payload.username }} to whitelist"
